spring.application.name=copypaste

# for more information, check link below:
spring.datasource.username=${COPYPASTE_SQL_USERNAME:root}
spring.datasource.password=${COPYPASTE_SQL_PASSWORD:}
spring.datasource.url=${COPYPASTE_DATASOURCE_URL:jdbc:h2:mem:test}

spring.jpa.hibernate.ddl-auto=create
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.publicKey=${JWT_PUBLIC_KEY:public.pem}
jwt.privateKey=${JWT_PRIVATE_KEY:private.pem}